# Generated by Django 6.0 on 2025-12-06 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('F', 'Farmer'), ('B', 'Buyer'), ('L', 'Logistics Agent')], default='F', max_length=1)),
                ('farm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('farm_size_hectares', models.FloatField(default=0.0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='croplisting',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_api.userprofile'),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_api.userprofile'),
        ),
        migrations.DeleteModel(
            name='FarmerProfile',
        ),
    ]
