# Generated by Django 6.0 on 2025-12-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_api', '0003_croplisting_created_at_croplisting_harvest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
