# Generated by Django 6.0 on 2025-12-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_api', '0004_userprofile_age_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='farm_type',
            field=models.CharField(choices=[('Family', 'Family Farm'), ('Private', 'Private Farm'), ('Govt', 'Government Subsidized'), ('Cooperative', 'Co-operative'), ('Other', 'Other')], default='Family', max_length=20),
        ),
    ]
